spring:
  profiles:
    include: secret

  datasource:
    platform: h2
    url: jdbc:h2:~/test;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    database-platform: H2
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop

  session:
    store-type: jdbc

logging:
  file:
    name: ${user.dir}/log/test/log
    max-history: 7
    max-size: 10MB