##GET http://localhost:8080/api/restaurant/list
#
#POST http://ec2-13-209-37-35.ap-northeast-2.compute.amazonaws.com:8080/api/restaurant
POST http://localhost:8080/api/restaurant
Content-Type: application/json

{
  "name" : "한글",
  "type": "KOREAN",
  "price" : "CHEAP",
  "location" : "ARTGATE",
  "deliveryable" : false,
  "latitude": 12,
  "longitude" : 24
}

###

#GET http://ec2-13-209-37-35.ap-northeast-2.compute.amazonaws.com:8080/api/restaurant/list
GET http://localhost:8080/api/restaurant/1

###
#POST http://ec2-13-209-37-35.ap-northeast-2.compute.amazonaws.com:8080/api/restaurant/special;
GET http://localhost:8080/api/restaurant/special;

Content-Type: application/json

{
  "special" : "ALLDAY"
}

###

PUT http://localhost:8080/api/restaurant/1/special/ALLDAY
#PUT http://ec2-13-209-37-35.ap-northeast-2.compute.amazonaws.com:8080/api/restaurant/2/special/ALLDAY

###

GET http://localhost:8080/api/restaurant/condition?type=KOREAN
