POST http://localhost:8080/restaurant
Content-Type: application/json

{
  "name": "창창",
  "type": "KOREAN",
  "price": "CHEAP",
  "location": "ARTGATE",
  "deliveryable": false,
  "latitude": 12,
  "longitude": 24
}

###

POST http://localhost:8080/member
Content-Type: application/json

{
  "name" : "sk",
  "email" : "sk@gmail.com",
  "picture" : "as"
}

###

#POST http://ec2-13-209-37-35.ap-northeast-2.compute.amazonaws.com:8080/restaurant/save
POST http://localhost:8080/restaurant/1/review
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiYXV0aCI6IlJPTEVfQURNSU4iLCJleHAiOjE2MzEwNzAwNzR9.XmulIvEmbuZnKaTDyF6ciXtdX92JtbH8TNiaYgnmSDSpmIDVi7Xl1Q8uqJOX2oA364Y8Tjiwl27WvyqwBLq2ew
Content-Type: application/json

{
  "description" : "good",
  "grade" : 3
}

###

GET http://localhost:8080/restaurant/1

###

#POST http://ec2-13-209-37-35.ap-northeast-2.compute.amazonaws.com:8080/restaurant/save
POST http://localhost:8080/restaurant/1/review
Content-Type: application/json

{
  "authorEmail" : "sk@gmail.com",
  "description" : "good",
  "grade" : 5
}

###
#GET http://localhost:8080/restaurant/1
GET http://localhost:8080/restaurant/1/review
#DELETE http://localhost:8080/restaurant/review/delete/3