POST http://localhost:8080/api/v1/user/login
Content-Type: application/json

{
  "name" : "sk",
  "email" : "sk@gmail.com",
  "picture" : "as"
}

###

#POST http://localhost:8080/api/v1/user/login
#Content-Type: application/json
#
#{
#  "name" : "ks",
#  "email" : "ks@gmail.com",
#  "picture" : "ks"
#}
#
####
#
#GET localhost:8080/api/v1/user/list
#
####
#
#DELETE  http://localhost:8080/api/v1/user/delete/2
#
####
#
#GET localhost:8080/api/v1/user/list
#
####
#
#DELETE  http://localhost:8080/api/v1/user/delete/sk@gmail.com
#
###

GET localhost:8080/api/v1/user/list