POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "name": "test",
  "email": "sketom77@gmail.com",
  "picture": "",
  "role": "ROLE_ADMIN",
  "socialTokenType": "GOOGLE",
  "socialToken": "ya29.a0ARrdaM_k8F5RFMeBKJgNhD7eUJ1jClxAN0hu0XLZf4jQy6lXqDzMEYohFq1jHABSZkH1bvPZBnnpdJnLp1WGZ3vTPwZ7dM-zLrMOcmJuZ0_Fw4HyM09VXEfO7iyfrQtwHm--qDIZniBAk6BRmGU6mb3-sYEu"
}

###

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "name": "test",
  "email": "sketom77@gmail.com",
  "picture": "",
  "role": "ROLE_ADMIN",
  "socialTokenType": "GOOGLE",
  "socialToken": "ya29.a0ARrdaM_k8F5RFMeBKJgNhD7eUJ1jClxAN0hu0XLZf4jQy6lXqDzMEYohFq1jHABSZkH1bvPZBnnpdJnLp1WGZ3vTPwZ7dM-zLrMOcmJuZ0_Fw4HyM09VXEfO7iyfrQtwHm--qDIZniBAk6BRmGU6mb3-sYEu"
}

###

GET http://localhost:8080/member/me
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTYzMDc3Mjg5MH0.V9B4x60HYt4iHGNDU5UFqtej5YhrabW5T5Nw7yGnDJUpMkHcU8rkhcevny4Wkfg6k6naTf7W883d3bRQPwWJkw

###

GET http://localhost:8080/member/list
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiYXV0aCI6IlJPTEVfQURNSU4iLCJleHAiOjE2MzA3NzY4ODN9.x2wIaKO0MDIhUWh1JvTn9E9bNYR2US63mAHVJIy66fdsSN7YYSE09g0ORFTlrx0vdpqJd7IlD09AEM9_tASZHw

###

#GET https://www.googleapis.com/userinfo/v2/me
#Authorization: Bearer ya29.a0ARrdaM-2ZqV13ngHmsCBa3juBwFENIrY660ih0rmyLkYxP3GfGAc20HH9d6lIZ3rQ1zAY0lxKgXyDO94tjlNl5r2KJPEeq441qHsvEaWt7HkqjwUzvFRyrHKue_ER36dZz2L4nG5E8GIFREauGfxR0ICKo8u
